# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0002_comic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='imgSrc',
            new_name='img_src',
        ),
        migrations.RenameField(
            model_name='anime',
            old_name='imgUrl',
            new_name='img_url',
        ),
        migrations.RenameField(
            model_name='anime',
            old_name='listUrl',
            new_name='list_url',
        ),
        migrations.RenameField(
            model_name='anime',
            old_name='watchUrl',
            new_name='watch_url',
        ),
        migrations.RenameField(
            model_name='comic',
            old_name='imgSrc',
            new_name='img_src',
        ),
        migrations.RenameField(
            model_name='comic',
            old_name='imgUrl',
            new_name='img_url',
        ),
        migrations.RenameField(
            model_name='comic',
            old_name='listUrl',
            new_name='list_url',
        ),
        migrations.RenameField(
            model_name='comic',
            old_name='watchUrl',
            new_name='watch_url',
        ),
    ]
